In [30]:
print ("Hello World!")

Hello World!


# My Heading
## Sub Heading
### Smaller Heading
#### Much Smaller Heading
stuff

~~more stuff~~
_List_
**Bold**

* stuff one
* stuff two

1. this
2. that

here, have ![this link](Numpy_Array_Dims.png)

In [32]:
name = "Samer"

In [34]:
name = "Ahmed"
#some intensive ML process

In [35]:
name
#something breaks

'Ahmed'

In [36]:
stats = np.array([[1,2,3],[4,5,6]])
stats

NameError: name 'np' is not defined

In [78]:
#Let's say we have this array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [79]:
# and we want it to be an 8x1 array
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [80]:
# or a 4x2 array
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
np.min(stats) #max etc

1

In [77]:
#or col by col
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [78]:
#Let's say we have this array
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [79]:
# and we want it to be an 8x1 array
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [80]:
# or a 4x2 array
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
!pwd

/Users/samer/Documents/Hanze Content/sse_intro_week/master_sse_22_23


In [38]:
!ls -la

total 1232
drwxr-xr-x@ 15 samer  staff     480 Sep  9 12:17 .
drwxr-xr-x@  4 samer  staff     128 Sep  9 12:17 ..
-rw-r--r--@  1 samer  staff    6148 Sep  9 11:55 .DS_Store
drwxr-xr-x@ 15 samer  staff     480 Sep  9 09:48 .git
drwxr-xr-x@  4 samer  staff     128 Sep  9 11:55 .ipynb_checkpoints
-rw-r--r--   1 samer  staff  103872 May 10 00:31 Indexing_Tricks_Qn.png
-rw-r--r--   1 samer  staff  160800 May 10 00:31 Indexing_Tricks_Soln.png
-rw-r--r--   1 samer  staff   54122 May 10 00:31 Memory_Management.png
-rw-r--r--@  1 samer  staff   39293 Sep  9 11:55 NumPy Tutorial.ipynb
-rw-r--r--   1 samer  staff  156653 May 10 00:31 Numpy_Array_Dims.png
-rw-r--r--   1 samer  staff   25028 Sep  8 09:39 Python_to_C.ipynb
-rw-r--r--   1 samer  staff      18 Sep  8 09:39 README.md
-rw-r--r--@  1 samer  staff    7465 Sep  9 12:21 This One.ipynb
-rw-r--r--   1 samer  staff   49053 May 10 00:31 array_initialisation_experiment.png
-rw-r--r--   1 samer  staff     133 May 10 00:31 data.txt


In [39]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [40]:
%pwd

'/Users/samer/Documents/Hanze Content/sse_intro_week/master_sse_22_23'

In [41]:
%ls -la

total 1240
drwxr-xr-x@ 15 samer  staff     480 Sep  9 12:23 ./
drwxr-xr-x@  4 samer  staff     128 Sep  9 12:23 ../
-rw-r--r--@  1 samer  staff    6148 Sep  9 11:55 .DS_Store
drwxr-xr-x@ 15 samer  staff     480 Sep  9 09:48 .git/
drwxr-xr-x@  4 samer  staff     128 Sep  9 11:55 .ipynb_checkpoints/
-rw-r--r--   1 samer  staff  103872 May 10 00:31 Indexing_Tricks_Qn.png
-rw-r--r--   1 samer  staff  160800 May 10 00:31 Indexing_Tricks_Soln.png
-rw-r--r--   1 samer  staff   54122 May 10 00:31 Memory_Management.png
-rw-r--r--@  1 samer  staff   39293 Sep  9 11:55 NumPy Tutorial.ipynb
-rw-r--r--   1 samer  staff  156653 May 10 00:31 Numpy_Array_Dims.png
-rw-r--r--   1 samer  staff   25028 Sep  8 09:39 Python_to_C.ipynb
-rw-r--r--   1 samer  staff      18 Sep  8 09:39 README.md
-rw-r--r--@  1 samer  staff    8990 Sep  9 12:23 This One.ipynb
-rw-r--r--   1 samer  staff   49053 May 10 00:31 array_initialisation_experiment.png
-rw-r--r--   1 samer  staff     133 May 10 00:31 data.txt


In [43]:
%%HTML
<iframe width="760" height="415" src="https://www.youtube.com/embed/PFDu9oVAE-g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [44]:
%%timeit
squares = [n*n for n in range(0,1000)]

60.6 µs ± 73.9 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [46]:
%%timeit
squares = []
for i in range(0,1000):
    squares.append(i*i)

86.9 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(10,5))
df.head()

0         1         2         3         4
0 -0.422858 -1.714760 -1.515658 -0.627868  2.086967
1 -0.877344  0.082369  0.810003  0.493752  1.283356
2  0.518445 -0.652265  0.779533  0.177805 -0.726516
3 -1.126071 -3.199954  1.405202 -1.281156 -1.846569
4 -1.271712  0.227322 -0.747672  1.148259 -0.492063